# Generated by Django 3.2.7 on 2021-09-09 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column_sep',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Разделитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='int_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='int_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='name_task',
            field=models.CharField(default=123, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
