# Generated by Django 3.2.7 on 2021-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('phone_num', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('title', models.CharField(max_length=50, verbose_name='Страна')),
                ('title2', models.CharField(max_length=50, verbose_name='Город')),
                ('task', models.CharField(max_length=50, verbose_name='Улица')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
