# Generated by Django 3.2.7 on 2021-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='account_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
