# Generated by Django 3.2.7 on 2021-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title2',
            field=models.CharField(default='some_value', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
    ]
