# Generated by Django 3.2.7 on 2021-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_account_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Полное имя'),
        ),
    ]
