# Generated by Django 3.2.7 on 2021-09-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210910_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='str_char',
            field=models.CharField(default=123, max_length=50, verbose_name='Скобки'),
            preserve_default=False,
        ),
    ]
