# Generated by Django 3.2.7 on 2021-10-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211005_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='country',
        ),
    ]
