# Generated by Django 3.2.7 on 2021-09-11 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_str_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf66b2cf-3b01-4b76-8231-fe50eac66aa2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
